#!/usr/bin/env python3
"""Build or verify the single-file distribution from the canonical modules."""

import argparse
import difflib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "jb.c"
PARTS = (
    "foundation.inc",
    "kernels_scalar.inc",
    "kernels_avx2.inc",
    "kernels_avx512.inc",
    "kernels_neon.inc",
    "kernels_dispatch.inc",
    "cuda.inc",
    "engine.inc",
    "api.inc",
    "cli_tests.inc",
)
NOTICE = "/* Generated by tools/amalgamate.py from the src modules; do not edit directly. */\n"


def generated() -> str:
    return NOTICE + "".join((ROOT / "src" / name).read_text() for name in PARTS)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generated()
    if args.check:
        current = OUTPUT.read_text()
        if current != result:
            print("".join(difflib.unified_diff(current.splitlines(True), result.splitlines(True),
                                                fromfile="jb.c", tofile="generated jb.c")))
            raise SystemExit("jb.c is not the current amalgamation")
    else:
        OUTPUT.write_text(result)


if __name__ == "__main__":
    main()
