#!/usr/bin/env python3
"""Build or verify the single-file distribution from the canonical modules."""

import argparse
import difflib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "jb.c"
PARTS = (
    "foundation.inc",
    "cuda.inc",
    "engine.inc",
    "api.inc",
    "cli_tests.inc",
)
BOUNDARIES = (
    "/* CUDA accelerator for the transformer layers.",
    "static DGTensor *dg_layer_tensor(DGModel *m, int l, const char *tail)",
    "struct jb_model {",
    "#ifndef JB_NO_MAIN\n/* Says on stderr",
)
NOTICE = "/* Generated by tools/amalgamate.py from the src modules; do not edit directly. */\n"


def split_initial() -> None:
    source = OUTPUT.read_text()
    if source.startswith(NOTICE):
        source = source[len(NOTICE) :]
    chunks = []
    at = 0
    for marker in BOUNDARIES:
        end = source.find(marker, at)
        if end < 0:
            raise SystemExit(f"cannot find split boundary: {marker}")
        chunks.append(source[at:end])
        at = end
    chunks.append(source[at:])
    directory = ROOT / "src"
    directory.mkdir(exist_ok=True)
    for name, chunk in zip(PARTS, chunks, strict=True):
        path = directory / name
        if path.exists():
            raise SystemExit(f"refusing to overwrite canonical module: {path}")
        path.write_text(chunk)


def generated() -> str:
    return NOTICE + "".join((ROOT / "src" / name).read_text() for name in PARTS)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--split-initial", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.split_initial:
        split_initial()
    result = generated()
    if args.check:
        current = OUTPUT.read_text()
        if current != result:
            print("".join(difflib.unified_diff(current.splitlines(True), result.splitlines(True),
                                                fromfile="jb.c", tofile="generated jb.c")))
            raise SystemExit("jb.c is not the current amalgamation")
    else:
        OUTPUT.write_text(result)


if __name__ == "__main__":
    main()
