/* Canonical modular translation unit. The public distribution is ../jb.c. */
#include "foundation.inc"
#include "kernels_scalar.inc"
#include "kernels_avx2.inc"
#include "kernels_avx512.inc"
#include "kernels_neon.inc"
#include "kernels_dispatch.inc"
#include "cuda.inc"
#include "engine.inc"
#include "api.inc"
#include "cli_tests.inc"
